step 2

diff --git a/.github/workflows/job-status.yaml b/.github/workflows/job-status.yaml
--- a/.github/workflows/job-status.yaml
+++ b/.github/workflows/job-status.yaml
@@ -8,12 +8,17 @@ jobs:
       - name: Step 1
         run: sleep 20
       - name: Step 2
+        id: step-2
         run: exit 1
+      - name: The demo step has failed
+        if: ${{ steps.step-2.conclusion == 'failure' }}
+        run: echo 'Step 2 has failed'
       - name: Runs on Failure
         if: failure()
         run: echo 'Runs on Failure'
       - name: Always Runs
         if: always()
+        # if: success() || failure()
         run: echo 'Always Runs'
       - name: Runs When Cancelled
         if: cancelled()
